Practical task for Block X Practice. RxJava
ArkHak/SimbirSoftRepo pull request #11
Opened 2023-07-19 21:29 UTC by ArkHak

2023-07-24 09:04 UTC, RebootSTR requested changes
+ Авторизация должна открывать перед сплешом
+ После авторизации кнопка назад не должна ее открывать
+ Странное поведение при нажатии на кнопку скрытия/показа пароля
+ Экран новостей пуст
+ Фича с сохранением текста в поисковой строке прикольная, но баганная) Текст стирается после нескольких переходов туда сюда. Либо чини, либо полностью фичу убери, так как это будет больше мешать пользователю, чем помогать (имхо)

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/data/datasource/local/NewsService.kt
Не используется, удали

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/AndroidManifest.xml
> +        <service
Не используется, удали

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/data/repository/NewsRepositoryImpl.kt
Мне не нравится логика: данные грузятся **_в кэш_** во время **_создания класса_** репозитория и больше никогда **_не обновляются_**.
1) чтобы реализовать кэш, нужно делать это по уму, с таймерами, инвалидацией и прочее. Просто создать переменную для новостей - это самый плохой кэш. 
2) данные должны подгружаться по запросу, а не при создании класса. При создании класса можно максимум инициализировать пустые или текстовые переменные (иначе поведение системы будет непредсказуемым)
3) Опять таки напоминаю, что ты подгружаешь новости из assets только потому что пока нет ретрофита (будет в будущих блоках), но вся система должна быть расчитана на реальное взаимодействие с бэком. А на бэке данные могут обновляться в любой момент. У тебя в приложении же они не могут сделать это физически, так как данные из ассетов ты грузишь всего 1 раз -  плохо

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/data/repository/NewsRepositoryImpl.kt
>      override fun getAllNews(): List<News> {
Для чего этот метод? Тебе нужно вытаскивать новости при помощи rx, а для этого у тебя уже есть метод

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/di/GsonModule.kt
> +        androidContext().assets.open("fake_news.json")
Ты не можешь дважды открыть ассеты, потому что у тебя используется single, вместо factory. Если заменишь, будет работать повторное открытие, НО я советую избавится от провайдинга инпут стрима. Это как-то не слишком надежно и уж точно не понятно. Ты можешь провайдить просто объект assets, или, в идеале, создать класс, который будет управлять всеми ассетами (AssetsManager) и будет отдавать уже конкретные новости и тд (но использовать его можно только в репозитории)

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/data/repository/NewsRepositoryImpl.kt
> +    private val inputStreamOriginal: InputStream,
название переменной не говорящее

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/MainActivity.kt
> +        mainViewModel.badgeSubject.subscribe() { count ->
в RX методы подписки возвращают объект Disposable. Эти объекты позволяют отписаться от источника данных, причем отписываться НУЖНО, иначе будет утечка памяти. RX, в отличии от LiveData и корутин внутри вьюмодели не связан с ЖЦ компонентов андроида, следовательно это нужно делать самостоятельно. Можешь глянуть видео по RX у Гладкова по этому поводу 

Касается всех мест где ты подписываешься, однако комментарий оставлю только один

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/authorization/AuthorizationFragment.kt
> +    @SuppressLint("UseCompatLoadingForDrawables")
прекрати игнорировать все предупреждения подряд)

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/authorization/AuthorizationFragment.kt
> +        ) { emailValid: Boolean, passwordValid: Boolean -> emailValid && passwordValid }
форматирование выгляжит ужасно) Выстави новую строку после ->

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/authorization/AuthorizationFragment.kt
> +        binding.loginButton.backgroundTintList = ColorStateList.valueOf(color)
Не правильное использование ColorStateList. Чтобы использовать это правильно, создай xml, в котором пропиши цвета для состояний isEnabled и прицепи его как background в верстке. Из кода останется лишь управлять isEnabled полем

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/authorization/AuthorizationFragment.kt
> +        val emailObserver = binding.emailEditText.textChanges().map {
логику валидации выноси во вьюмодель

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/data/repository/NewsRepositoryImpl.kt
> +    override fun setIsViewedNews(idNews: Int) {
![image](https://github.com/ArkHak/SimbirSoftRepo/assets/46527979/f76985d3-f3ca-4f8c-9d66-45dce849acd6)

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/help/HelpFragment.kt
> +            showLoadingData()
По хорошему, в архитктуре MVVM этим должна управлять вьюмодель

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/help/HelpViewModel.kt
> +    private val executor = Executors.newSingleThreadExecutor()
убираем екзекьюторы, меняем на rx

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/help/HelpViewModel.kt
> +        private const val TIMEOUT = 5000L
таймауты можешь уменьшить до 1к, уже не так принципиально

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/main/NewsViewModel.kt
> +    init {
почему у тебя новости из 2х разных мест загружаются?

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/events/SearchEventsFragment.kt
> +    companion object {
зачем выносить в компаньон?

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/events/SearchEventsFragment.kt
> +        binding.searchEventsItemRecyclerView.addItemDecoration(
нечитаемое месиво, лучше разделить на переменные

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/events/SearchEventsFragment.kt
> +        binding.searchEventsItemRecyclerView.addItemDecoration(
![image](https://github.com/ArkHak/SimbirSoftRepo/assets/46527979/ea5505a6-9f81-4b87-8405-90f105b6ce24)

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/main/SearchFragment.kt
> +        searchObservable
логику во вьюмодель

2023-07-24 09:04 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/nko/SearchNKOFragment.kt
> +        private val ID_TITLE = R.string.hint_input_name_organization
почему в компаньоне

2023-07-24 18:01 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/data/datasource/local/NewsService.kt
+++

2023-07-24 18:01 UTC, ArkHak commented on app/src/main/AndroidManifest.xml
> +        <service
++++

2023-07-24 18:07 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/help/HelpViewModel.kt
> +        private const val TIMEOUT = 5000L
+++

2023-07-24 18:19 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/authorization/AuthorizationFragment.kt
> +    @SuppressLint("UseCompatLoadingForDrawables")
((++

2023-07-24 18:28 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/authorization/AuthorizationFragment.kt
> +        ) { emailValid: Boolean, passwordValid: Boolean -> emailValid && passwordValid }
+++

2023-07-24 18:35 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/authorization/AuthorizationFragment.kt
> +        binding.loginButton.backgroundTintList = ColorStateList.valueOf(color)
+++

2023-07-24 20:49 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/authorization/AuthorizationFragment.kt
> +        val emailObserver = binding.emailEditText.textChanges().map {
+++

2023-07-25 18:40 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/events/SearchEventsFragment.kt
> +    companion object {
там была какая-то логика и я ее придерживался

2023-07-25 18:49 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/events/SearchEventsFragment.kt
> +        binding.searchEventsItemRecyclerView.addItemDecoration(
+++

2023-07-25 18:51 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/nko/SearchNKOFragment.kt
> +        private val ID_TITLE = R.string.hint_input_name_organization
+++

2023-07-25 19:49 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/main/SearchFragment.kt
> +        searchObservable
++++

2023-07-25 21:24 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/MainActivity.kt
> +        mainViewModel.badgeSubject.subscribe() { count ->
+++

2023-07-26 19:51 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/data/repository/NewsRepositoryImpl.kt
> +    override fun setIsViewedNews(idNews: Int) {
+++

2023-07-26 20:02 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/help/HelpFragment.kt
> +            showLoadingData()
+++

2023-07-26 20:11 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/help/HelpViewModel.kt
> +    private val executor = Executors.newSingleThreadExecutor()
+++

2023-07-26 20:34 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/di/GsonModule.kt
> +        androidContext().assets.open("fake_news.json")
++++

2023-07-26 20:34 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/data/repository/NewsRepositoryImpl.kt
> +    private val inputStreamOriginal: InputStream,
+++

2023-07-26 21:57 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/main/NewsViewModel.kt
> +    init {
+++

2023-07-27 18:03 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/data/repository/NewsRepositoryImpl.kt
>      override fun getAllNews(): List<News> {
++++

2023-07-27 18:03 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/data/repository/NewsRepositoryImpl.kt
++++

2023-08-01 06:52 UTC, RebootSTR approved these changes
Проверено

2023-08-01 18:46 UTC, merged