Practical task for Block XI Practice. Coroutines
ArkHak/SimbirSoftRepo pull request #12
Opened 2023-08-01 21:28 UTC by ArkHak

- add Coroutines;
- replaced RxJava and BehaviorSubject with Flow and MutableStateFlow in SearchScreens, NewsRepository, MainActivity;

2023-08-06 10:49 UTC, RebootSTR requested changes

2023-08-06 10:49 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/data/repository/NewsRepositoryImpl.kt
> +    private fun getNewsFromAssetsByFlow(): Flow<List<News>> = flow {
Не обязательно оборачивать во flow все методы, особенно приватные. Этот метод можно было оставить синхронным, без оборачивания во флоу, потому что ты все равно вызываешь его в контексте корутины и он ничего не заблокирует. Ничего плохого в твоем способе нет, просто для информации)

2023-08-06 10:49 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/detail/NewsDetailViewModel.kt
>      fun getNews(newsId: Int) {
Не сочти за излишнюю душноту, но метод ничего не возвращает, чтобы называться GET

2023-08-06 10:49 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/MainActivityViewModel.kt
> +        viewModelScope.launch {
Для StateFlow можно ограничиться вызовом tryEmit, который не требует корутины для вызова

2023-08-06 10:49 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/events/SearchEventsViewModel.kt
>      fun cleanEventList() {
А почему у тебя в этом методе используются корутины для обновления liveData? LiveData должна обновляться исключительно в UI потоке

2023-08-06 10:49 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/main/SearchViewModel.kt
> +            searchQueryFlow.emit(query)
Эмитить можно через tryEmit

2023-08-06 19:59 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/main/SearchViewModel.kt
> +            searchQueryFlow.emit(query)
+++

2023-08-06 20:04 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/data/repository/NewsRepositoryImpl.kt
> +    private fun getNewsFromAssetsByFlow(): Flow<List<News>> = flow {
понял, спасибо)
просто в задании вроде было типа приходят два потока и их надо слить в один
потому пока оставил

2023-08-06 20:07 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/detail/NewsDetailViewModel.kt
>      fun getNews(newsId: Int) {
+++
всё верно)

2023-08-06 20:08 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/MainActivityViewModel.kt
> +        viewModelScope.launch {
+++

2023-08-06 20:41 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/events/SearchEventsViewModel.kt
>      fun cleanEventList() {
.flowOn(Dispatchers.Main)
  так на main потоке)
  это нужно для collect

2023-08-06 20:53 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/main/SearchViewModel.kt
> +            searchQueryFlow.emit(query)
у MutableShareFlow так не работало, пришлось заменить на MutableStateFlow

2023-08-13 16:18 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/events/SearchEventsViewModel.kt
>      fun cleanEventList() {
![image](https://github.com/ArkHak/SimbirSoftRepo/assets/46527979/002a2c3d-d14d-4f0a-9b28-1a9a4c5e8615)

2023-08-13 16:21 UTC, RebootSTR approved these changes

2023-08-13 19:33 UTC, merged