Compose
ArkHak/SimbirSoftRepo pull request #19
Opened 2023-09-16 19:02 UTC by ArkHak

- add Compose;
- add AuthorizationComposeFragment;
- add NewsComposeFragment;

2023-09-19 06:43 UTC, RebootSTR requested changes

2023-09-19 06:43 UTC, RebootSTR commented on feature_authorization/src/main/java/ru/mys_ya/feature_authorization/ui/composeunit/EmailTextField.kt
> +        modifier = modifier.fillMaxWidth(),
Мое мнение: размерами компонента должен управлять тот, кто использует этот компонент. Делая тут fillMaxWidth ты создаешь ситуацию, что теперь везде, где бы ты не установил EmailTextField, он будет "match_parent"

2023-09-19 06:43 UTC, RebootSTR commented on feature_authorization/src/main/java/ru/mys_ya/feature_authorization/ui/composeunit/PasswordTextField.kt
> +        visualTransformation =
поправь форматирование, чего у тебя равенство висит пустое (визуально такое ощущение)

2023-09-19 06:43 UTC, RebootSTR commented on feature_news/src/main/java/ru/mys_ya/feature_news/ui/news/main/NewsFragment.kt
> +//            val action = NewsFragmentDirections.actionFragmentNewsToNewsDetailFragment(idItem)
комментарии удаляй, не храни в коде. Комментарии с кодом бесполезны, так как не хранят никакой информации о том, что они делают и по какой причине закоммичены. Может быть ты уже сделал навигацию, а может и не сделал, точно я знать все равно не могу.

2023-09-19 06:43 UTC, RebootSTR commented on feature_news/src/main/java/ru/mys_ya/feature_news/ui/news/main/NewsFragment.kt
> +//            val action = NewsFragmentDirections.actionFragmentNewsToNewsDetailFragment(idItem)
Если комментарий тут нужен по какой-то причине, то оставляй рядом с ним тудушку и описание

2023-09-19 06:43 UTC, RebootSTR commented on feature_authorization/src/main/java/ru/mys_ya/feature_authorization/ui/AuthorizationScreen.kt
При перевороте экрана, не могу ничего ввести (нет скролла)

2023-09-19 06:43 UTC, RebootSTR commented on feature_news/src/main/java/ru/mys_ya/feature_news/ui/news/main/NewsFragment.kt
Текст внутри новости слишком близко к картинке, перепроверь макет
При перевороте экрана новости с рандомной шириной

2023-09-19 06:49 UTC, RebootSTR commented
На экране категорий помощи при перевороте начинается вечная загрузка, что-то у тебя там сломано тоже

2023-09-20 20:29 UTC, ArkHak commented on feature_authorization/src/main/java/ru/mys_ya/feature_authorization/ui/composeunit/EmailTextField.kt
> +        modifier = modifier.fillMaxWidth(),
++++

2023-09-20 20:31 UTC, ArkHak commented on feature_authorization/src/main/java/ru/mys_ya/feature_authorization/ui/composeunit/PasswordTextField.kt
> +        visualTransformation =
+++

2023-09-20 20:34 UTC, ArkHak commented on feature_news/src/main/java/ru/mys_ya/feature_news/ui/news/main/NewsFragment.kt
> +//            val action = NewsFragmentDirections.actionFragmentNewsToNewsDetailFragment(idItem)
+++

2023-09-20 21:01 UTC, ArkHak commented on feature_authorization/src/main/java/ru/mys_ya/feature_authorization/ui/AuthorizationScreen.kt
+++

2023-09-20 21:19 UTC, ArkHak commented on feature_news/src/main/java/ru/mys_ya/feature_news/ui/news/main/NewsFragment.kt
1. Не знаю попал или нет - но поправил чуть)
2. Поправил. сразу там два косяка убрал)

2023-09-20 21:34 UTC, merged