Базовое задание по Блоку III. Java. Часть 2
ArkHak/SimbirSoftRepo pull request #2
Opened 2023-05-28 22:09 UTC by ArkHak

ClassesBlock - done;
StringsTraining - done;
CollectionsBlock - done;

2023-05-29 17:35 UTC, RebootSTR requested changes

2023-05-29 17:35 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +        public void getValues() {
Функция ничего не возвращает, только выводит переменные на экран. Нейминг не подходящий

2023-05-29 17:35 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +        public void setValues(int value1, int value2) {
Переменных 2, следовательно и функций для их изменения тоже должно быть 2

2023-05-29 17:35 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +            System.out.println(Arrays.toString(array));
Есть задача вывести массив (читай класс) на экран. Она делится на 2 подзадачи - 1) засунуть этот массив в строку, 2) Вывести строку на экран. Со вторым заданием ты справился, но с первым не очень) Первое что приходит на ум когда идет речь о том, чтобы превратить класс в строку - метод toString. Стоит его переопределить, если есть необходимость печатать массив на экран

2023-05-29 17:35 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +        public Triangle(double sideA, double sideB, double sideC) {
Интересное решение, но обычно все фигуры описывают минимальными единицами. В случае n-угольников, это точки в некоторой системе координат, в случае окружности радиус. Можно не переделывать, но этот ньюанс запомни

2023-05-29 17:35 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +    public class Watch {
не доделал задание, смотри на последний пункт

2023-05-29 17:35 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +        private Double Debit;
хранишь деньги в Double? Так делать нельзя) Используй Decimal

2023-05-29 17:35 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +            System.out.println("ID: " + this.getId());
См. 2 задание в этом файле

2023-05-29 17:35 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +        public void getSubscribesForWitchUrbanNegotiationsExceedsSpecified(double time) {
опять get ничего не возвращает. Так как тут у тебя есть место вызова (main), а класс содержит какие-то данные, то он не должен ничего выводить (print), только хранить данные и, возможно, обрабатывать их. Все sout выноси из класса

2023-05-29 17:35 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +            System.out.println("Адрес: " + this.getAddress());
Несколько идущих подряд принтов - плохо. В случае нескольких потоков весь вывод может быть перемешан

2023-05-29 17:35 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +        public boolean isInBlackList(Client client) {
Если клиент в черном списке, он не должен иметь возможности создать заказ

2023-05-29 17:35 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +        public boolean isInBlackList(Client client) {
Тебе еще нужен класс для магазина, в котором будет вся логика друг с другом взаимодействовать

2023-05-29 17:35 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/collections/CollectionsBlock.java
>       * @throws NullPointerException если один из параметров null
Проверки на null нет

2023-05-29 19:43 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +        public void getValues() {
+

2023-05-29 19:44 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +        public void setValues(int value1, int value2) {
+

2023-05-29 19:51 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +            System.out.println(Arrays.toString(array));
+

2023-05-29 19:53 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +        public Triangle(double sideA, double sideB, double sideC) {
++++

2023-05-29 20:01 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +    public class Watch {
+++
я это понял как setHours, setMinutes, setSeconds
но дописал)

2023-05-29 20:16 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +        private Double Debit;
+++

2023-05-29 20:21 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/collections/CollectionsBlock.java
>       * @throws NullPointerException если один из параметров null
(@NonNull List<T> firstList, @NonNull List<T> secondList) throws NullPointerException
Параметры же помечены как @NonNull, и если не так, то бросается NullPointerException.
Но прописал ручками

2023-05-29 20:43 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +            System.out.println("ID: " + this.getId());
это про переопределение метода toString? оксид

2023-05-29 20:59 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +        public void getSubscribesForWitchUrbanNegotiationsExceedsSpecified(double time) {
++++

2023-05-29 21:02 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +            System.out.println("Адрес: " + this.getAddress());
+++

2023-05-29 22:00 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +        public boolean isInBlackList(Client client) {
+++

2023-06-05 17:05 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +            System.out.println(array);
System.out.println(this);
Иначе зачем ты оверрайдил toString()?)

2023-06-05 17:05 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +            return "ID:" + id + "\n" +
Строки в джаве складывать нельзя, особенно в таких количествах)

2023-06-05 17:22 UTC, RebootSTR approved these changes

2023-06-05 17:57 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +            System.out.println(array);
исправил

2023-06-05 17:59 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/classes/ClassesBlock.java
> +            return "ID:" + id + "\n" +
Тогда какое лучше решение?

2023-06-05 17:59 UTC, merged