Практическое задание по Блоку VI. Верстка
ArkHak/SimbirSoftRepo pull request #6
Opened 2023-06-12 22:05 UTC by ArkHak

2023-06-13 11:20 UTC, RebootSTR requested changes

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +    private val viewModel: ProfileViewModel by lazy {
by viewmodels()

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +            .observe(viewLifecycleOwner, Observer<User> { renderData(it) })
Писать Observer<User> не обязательно

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileViewModel.kt
> +    private val liveDataForViewToObserve: MutableLiveData<User> = MutableLiveData(),
Через конструктор в класс прокидываем только то, что должно подключаться извне. В данном случае вьюмодель хранит в себе LiveData, она не должна быть в конструкторе

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileViewModel.kt
> +    fun getData(): LiveData<User> {
В котлине есть геттеры, функции вида getSome() - java style

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileViewModel.kt
> +        val friendList = mutableListOf<Friend>(
я понимаю, что данные тестовые, но даже их можно вынести в отдельную функцию (например, loadFriends)

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +        val adapter = ProfileAdapter(friendsList)
У тебя адаптер создается заново при каждом изменении данных

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +        val adapter = ProfileAdapter(friendsList)
Так как это функция init, то вызывай ее не в renderData, а в onViewCreated

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileAdapter.kt
> +    inner class ViewHolder(private val binding: ItemFriendsBinding) :
Вытаскивай холдер из класса адаптера. Сейчас это не создает тебе никаких проблем, но в будущем, если ты привыкнешь так делать, возникнет соблазн использовать параметры адаптера внутри холдера, а это плохо

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/MainActivity.kt
> +    private val listener by lazy {
слишком общий нейминг

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/layout/splash_screen.xml
неправильный нейминг, сделай fragment_splash

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +                android:layout_width="wrap_content"
По возможности, там где ширина вью может меняться, лучше ширину указывать match_parent, чтобы на макете был виден его максимальный размер элемента
![image](https://github.com/ArkHak/SimbirSoftRepo/assets/46527979/92a49596-dad9-4907-9b25-b02c9f904377)

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +                android:layout_width="wrap_content"
Посмотри и исправь все, что страдает подобной штукой

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +                <TextView
У Switch есть текст, ну нужно делать его отдельно

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +            <com.google.android.material.button.MaterialButton
Кнопка должна быть светлее и текст внутри должен быть "шире" 
![image](https://github.com/ArkHak/SimbirSoftRepo/assets/46527979/8b95bf6f-7508-4baf-ae13-ba079942c828)

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +            <View
Divider'ы должны быть во всю ширину экрана
![image](https://github.com/ArkHak/SimbirSoftRepo/assets/46527979/e5b50e15-3e77-48fc-98a1-cf36ee8b66ab)

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/values/dimens.xml
> +    <dimen name="margin_vertical_logout_button">16dp</dimen>
Разрешаю не использовать dimens на все подряд) Используй только в случае если значение может быть переиспользовано, например высота кнопки, которая встречается много где в приложении или высота тулбара. Делать dimens только ради того чтобы использовать его - не нужно.

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +                android:layout_marginVertical="@dimen/margin_vertical_logout_button"
неправильный отступ

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/values/style.xml
> +        <item name="android:layout_marginHorizontal" tools:targetApi="o">
1) Если api будет не "о", у тебя поедет верстка, потому что свойство не применится
2) Не выноси сюда отступы, достаточно будет вынести в дименс, если так хочешь

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +                android:id="@+id/spacer_after_info_block"
ширина не совпала с макетом

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +                android:text="@string/birthday_title" />
текст неверный

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +            <ImageView
![image](https://github.com/ArkHak/SimbirSoftRepo/assets/46527979/9dea36bf-6bfa-4fa8-9e99-87d09b9cb4c3)

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/layout/activity_main.xml
> +        <androidx.appcompat.widget.Toolbar
тулбар не скрывается

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/layout/activity_main.xml
> +        <androidx.appcompat.widget.Toolbar
По поводу appbar - он может требоваться не на всех экранах, следовательно нужно либо делать его только там, где он нужен, либо иметь возможность его скрывать
Что именно выбрать решай сам, но первый вариант сейчас будет проще

2023-06-13 11:20 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +            <androidx.recyclerview.widget.RecyclerView
По поводу друзей - как и в макете, максимальное количество должно быть 3. Следовательно список не прокручивается, и эффекта прокручивания тоже быть не должно

2023-06-13 11:25 UTC, RebootSTR requested changes

2023-06-13 11:25 UTC, RebootSTR commented on app/src/main/res/layout/activity_main.xml
> +    <com.google.android.material.bottomnavigation.BottomNavigationView
Названия не должны пропадать
![image](https://github.com/ArkHak/SimbirSoftRepo/assets/46527979/255c021e-a99c-4cef-9de3-6abd52bdd48f)

2023-06-13 19:24 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +    private val viewModel: ProfileViewModel by lazy {
++
не знаю, почему сразу так не сделал

2023-06-13 19:24 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +            .observe(viewLifecycleOwner, Observer<User> { renderData(it) })
++

2023-06-13 19:26 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileViewModel.kt
> +    private val liveDataForViewToObserve: MutableLiveData<User> = MutableLiveData(),
++
тут скорее я сразу создавал через val, но да)

2023-06-13 19:30 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileViewModel.kt
> +    fun getData(): LiveData<User> {
а как же приватить поля?

2023-06-13 19:42 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileViewModel.kt
> +    fun getData(): LiveData<User> {
++

2023-06-13 19:45 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileViewModel.kt
> +        val friendList = mutableListOf<Friend>(
++

2023-06-13 20:01 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileAdapter.kt
> +    inner class ViewHolder(private val binding: ItemFriendsBinding) :
+++
делал и так и так, просто решил сделать побыстрее)

2023-06-13 20:04 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +        val adapter = ProfileAdapter(friendsList)
+++

2023-06-13 20:13 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/MainActivity.kt
> +    private val listener by lazy {
bottomNavigationPanelController - более конкретный)

2023-06-13 20:17 UTC, ArkHak commented on app/src/main/res/layout/splash_screen.xml
+++

2023-06-13 20:21 UTC, ArkHak commented on app/src/main/res/layout/fragment_profile.xml
> +                android:layout_width="wrap_content"
+++

2023-06-13 20:27 UTC, ArkHak commented on app/src/main/res/layout/fragment_profile.xml
> +                <TextView
ОГО!+++

2023-06-13 20:31 UTC, ArkHak commented on app/src/main/res/layout/fragment_profile.xml
> +            <com.google.android.material.button.MaterialButton
++

2023-06-13 20:53 UTC, ArkHak commented on app/src/main/res/layout/fragment_profile.xml
> +            <View
++

2023-06-13 20:58 UTC, ArkHak commented on app/src/main/res/values/dimens.xml
> +    <dimen name="margin_vertical_logout_button">16dp</dimen>
+

2023-06-13 21:00 UTC, ArkHak commented on app/src/main/res/layout/fragment_profile.xml
> +                android:layout_marginVertical="@dimen/margin_vertical_logout_button"
++
подправил, но думал как сделал я - лучше)

2023-06-13 21:05 UTC, ArkHak commented on app/src/main/res/values/style.xml
> +        <item name="android:layout_marginHorizontal" tools:targetApi="o">
++

2023-06-13 21:06 UTC, ArkHak commented on app/src/main/res/layout/fragment_profile.xml
> +                android:id="@+id/spacer_after_info_block"
расширил

2023-06-13 21:08 UTC, ArkHak commented on app/src/main/res/layout/fragment_profile.xml
> +                android:text="@string/birthday_title" />
++

2023-06-13 21:12 UTC, ArkHak commented on app/src/main/res/layout/activity_main.xml
> +    <com.google.android.material.bottomnavigation.BottomNavigationView
+++

2023-06-14 20:53 UTC, ArkHak commented on app/src/main/res/layout/fragment_profile.xml
> +            <ImageView
+++

2023-06-14 20:53 UTC, ArkHak commented on app/src/main/res/layout/activity_main.xml
> +        <androidx.appcompat.widget.Toolbar
+++

2023-06-14 20:53 UTC, ArkHak commented on app/src/main/res/layout/fragment_profile.xml
> +            <androidx.recyclerview.widget.RecyclerView
+++

2023-06-15 08:36 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileViewModel.kt
> +        val friendList = mutableListOf<Friend>(
Я имел ввиду функцию, которая ничего не возвращает и содержит внутри себя всю логику по обновлению данных. Загрузку (создание) и отправку в LiveData

2023-06-15 08:42 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +                android:layout_marginVertical="@dimen/margin_vertical_logout_button"
Нужно по макету делать)

2023-06-15 08:46 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +            <androidx.recyclerview.widget.RecyclerView
Просто добить тестовые данные до 3х - не вариант) В реальном проекте список друзей ты получал бы из сети или бд. Следовательно тебе пришлось бы вручную сокращать их количество до 3х. Сделать это можно в той же вьюмодли (но желательно сразу перенести получение данных в юзкейс и ограничивать там)

2023-06-15 08:48 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +            <com.google.android.material.button.MaterialButton
Кнопка все еще не совпадает с дизайном) 
(углы)

2023-06-15 08:57 UTC, RebootSTR requested changes

2023-06-15 08:57 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +            <ImageView
Я не понял почему у тебя картинка нормально встала без android:adjustViewBounds="true"

2023-06-15 08:57 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileAdapter.kt
> +        val height = parent.measuredHeight / 3
Это что? Это зачем?

2023-06-15 08:57 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +                android:nestedScrollingEnabled="true"
overScrollMode="never"

2023-06-15 08:57 UTC, RebootSTR commented on app/src/main/res/layout/fragment_profile.xml
> +            <androidx.recyclerview.widget.RecyclerView
Кстати, тут можно сразу указать лейаут менеджер, чтобы не указывать его в коде

2023-06-15 08:57 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileViewHolder.kt
> +        binding.itemName.text = friend.name
А про аватарки друзей забыл?

2023-06-15 17:28 UTC, ArkHak commented on app/src/main/res/layout/fragment_profile.xml
> +            <ImageView
хах хз)
но добавил - на превьюхе лучше тогда выглядит

2023-06-15 17:29 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileAdapter.kt
> +        val height = parent.measuredHeight / 3
как раз ограничение для 3 элементов - размер всего

2023-06-15 17:30 UTC, ArkHak commented on app/src/main/res/layout/fragment_profile.xml
> +                android:nestedScrollingEnabled="true"
++++

2023-06-15 17:36 UTC, ArkHak commented on app/src/main/res/layout/fragment_profile.xml
> +            <androidx.recyclerview.widget.RecyclerView
да, кинул туда

2023-06-15 17:53 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileViewHolder.kt
> +        binding.itemName.text = friend.name
+++

2023-06-15 18:21 UTC, ArkHak commented on app/src/main/res/layout/fragment_profile.xml
> +            <com.google.android.material.button.MaterialButton
добавил тени и поставил углы как указано в макете

2023-06-15 19:08 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileViewModel.kt
> +        val friendList = mutableListOf<Friend>(
+++

2023-06-15 19:58 UTC, merged