Fragments
ArkHak/SimbirSoftRepo pull request #7
Opened 2023-06-22 22:17 UTC by ArkHak

- DialogFragment - done; (task2)
- HelpFragment - done; (task3)
- SearchFragment - done; (task4)

2023-06-23 08:56 UTC, RebootSTR requested changes

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileImageDialogFragment.kt
> +    val clickListenerCreatePhoto: (ItemPhotoSelector) -> Unit,
ошибка невероятного масштаба, аргументы в фрагменты вставлять НЕЛЬЗЯ

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileImageDialogFragment.kt
> +        view.findViewById<View>(R.id.item_select_photo).apply {
Почему binding не используешь?

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +    private fun warningPictureToast() {
Лучше назвать showWarningPictureToast, чтобы лучше читалось в местах, где он вызывается

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +            binding.root.context,
Для тостов можно использовать requreContext, не обязательно тащить вьюшный котекст

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +    private val permission =
Структура класса: переменные, конструктор, методы

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +    private val camera =
Структура класса: переменные, конструктор, методы
Лучше назвать переменную cameraActivityLaunher, чтобы было понятно что это в месте вызова

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +            binding.profileAvatar.setImageBitmap(bitmap)
А сохранение фотки так и не реализовал, получается? Сделай так, чтобы картинка переживала закрытие приложения. При удалении картинки, выставляй дефолтную с тем мужичком. Когда будешь реализовывать, держи в голове инфу о том, что помимо напрямую сделанной фотки тебе потом нужно будет сделать еще и так, чтобы можно было из галереи картинку вставлять, то есть должно быть +- универсальное решение

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/help/HelpFragment.kt
> +        adapter.updateHelpCategoryList(helpViewModel.loadHelpCategory())
Я понимаю, что ты идешь по пути наименьшей сложности и быстроты, но приучайся к тому, чтобы разделять инициализацию чего либо, и загрузку данных. Вынеси обновление данных в отдельный метод. Также есть вопросы по неймингу.
initAdapter - инициализация АДАПТЕРА для ресайклера
initRecycler - инициализация РЕСАЙКЛЕРА для отображения данных
Инициализация ресайклера может включать в себя инициализацию адаптера, так как он нужен для его работы, но наоборот быть не должно.

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/help/HelpFragment.kt
> +    private lateinit var adapter: HelpAdapter
Старайся по минимуму использовать lateinit. Тут можно сделать by lazy {}

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/utils/Utils.kt
> +class MarginDecoration(context: Context) : RecyclerView.ItemDecoration() {
Лучше вынести как отдельный файл MarginDecoration. Держать все утилиты в одном файле плохая идея. Так можно делать только есть внутри файла хранятся методы, объединенные смыслом (например методы для работы с текстом)

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/utils/Utils.kt
> +        margin = context.resources.getDimensionPixelSize(R.dimen.item_helps_margin)
присваивать значение можно и без init {} блока)

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchByNKOFragment.kt
чтобы дерево файлом было более читаемым, можешь разбить его на более мелкие пакеты, например main nko и events

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
не делай слипание переменных и методов, оставляй расстояние в одну строку

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchFragmentViewPagerAdapter.kt
> +enum class SearchTypeNumber(val number: Int) {
1. лучше вынести как отдельный класс
2. у енамов есть свойство ordinal, которое возвращает индекс объекта, в порядке записи его в енам
3. можешь в конструктор добавить ресурс названия вкладки, будет более логичная структура

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchByNKOFragment.kt
> +    private fun initAdapter() {
Аналогичные замечания как я уже где-то оставлял

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchByNKOFragment.kt
> +        adapter.updateEventList(searchViewModel.getRandomList())
Тут подразумевается загрузка данных "из сети", поэтому напрямую вытащить данные у вьюмодельки мы не можем. Реализуй при помощи метода loadResultList (который срабатывает тогда, когда нужно обновить данные) и LiveData содержащей список с данными для отображения. Кароче как со списком друзей в профиле. Привыкай и набивай руку к такому способу получения данных, так как программирование приложений всегда ассинхронное.

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchByNKOFragment.kt
> +    private var firstInit = false
не понял зачем этот параметр. ты его нигде не ставишь в false, а в true он превращается сразу при загрузке экрана

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchViewModel.kt
> +    private val fooEventsList = listOf(
соблюдай порядок переменных и методов в классе

2023-06-23 08:56 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchFragment.kt
> +        binding.searchFragmentViewPager.setPageTransformer(ZoomOutPageTransformer())
прикольно, но не понятно зачем) Обычно если нужна супер анимация, об этом просят в явном виде) Пусть остается

2023-06-25 20:55 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileImageDialogFragment.kt
> +    val clickListenerCreatePhoto: (ItemPhotoSelector) -> Unit,
++ на resultApi

2023-06-25 20:56 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileImageDialogFragment.kt
> +        view.findViewById<View>(R.id.item_select_photo).apply {
потому что он тут немного не стандартно используется
+ от Розова через by viewBinding() работает не корректно раздутие layout

2023-06-25 20:57 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +    private fun warningPictureToast() {
+++

2023-06-25 20:58 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +            binding.root.context,
++

2023-06-25 21:00 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +    private val permission =
+++

2023-06-25 21:01 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +    private val camera =
+++

2023-06-25 21:10 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/profile/ProfileFragment.kt
> +            binding.profileAvatar.setImageBitmap(bitmap)
-+

2023-06-25 21:48 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/help/HelpFragment.kt
> +        adapter.updateHelpCategoryList(helpViewModel.loadHelpCategory())
++

2023-06-25 21:49 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/help/HelpFragment.kt
> +    private lateinit var adapter: HelpAdapter
++

2023-06-25 21:51 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/utils/Utils.kt
> +class MarginDecoration(context: Context) : RecyclerView.ItemDecoration() {
++

2023-06-25 21:53 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/utils/Utils.kt
> +        margin = context.resources.getDimensionPixelSize(R.dimen.item_helps_margin)
+++

2023-06-25 21:57 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchByNKOFragment.kt
+++

2023-06-25 21:58 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
++

2023-06-25 22:05 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchFragmentViewPagerAdapter.kt
> +enum class SearchTypeNumber(val number: Int) {
+++

2023-06-25 22:08 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchByNKOFragment.kt
> +    private fun initAdapter() {
++

2023-06-25 22:32 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchByNKOFragment.kt
> +        adapter.updateEventList(searchViewModel.getRandomList())
+++

2023-06-25 22:32 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchByNKOFragment.kt
> +    private var firstInit = false
+++

2023-06-25 22:33 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchViewModel.kt
> +    private val fooEventsList = listOf(
++

2023-06-27 18:30 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchViewModel.kt
Эта вьюмоделька исключительно для NKO, я так понимаю? Если да, то переименуй и убери в пакет для нко

2023-06-27 18:30 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/main/SearchFragment.kt
> +            SearchTypeNumber.EVENTS.ordinal -> return getString(SearchTypeNumber.EVENTS.titleId)
Как ты считаешь красивый ли тут when? Мне кажется, что нет) Инструкция как сделать красиво (на реальных проектах пригодилось много раз): Создай в енаме метод, который парсит какой-то объект (в данном случае индекс) в объект енама. Тогда здесь у тебя будет вот такой код:
`return getString(SearchTypeNumber.mapByIndex().titleId)`

PS. не забывай о том, что first кидает исключения

2023-06-27 18:30 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/nko/SearchNKOFragment.kt
> +    private fun renderData(nkoList: List<Event>?) {
Нулабельность лишняя

2023-06-27 18:51 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/SearchViewModel.kt
++ думал потом как общую заюзать

2023-06-27 18:52 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/nko/SearchNKOFragment.kt
> +    private fun renderData(nkoList: List<Event>?) {
+++

2023-06-27 19:11 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/search/main/SearchFragment.kt
> +            SearchTypeNumber.EVENTS.ordinal -> return getString(SearchTypeNumber.EVENTS.titleId)
+++

2023-06-27 19:22 UTC, merged