Data structures
ArkHak/SimbirSoftRepo pull request #8
Opened 2023-07-01 21:57 UTC by ArkHak

2023-07-02 17:25 UTC, RebootSTR requested changes
Отлично сделано!!

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/SimbirSoftApplication.kt
> +class SimbirSoftApplication : Application() {
Не критично, но называть класс в честь компании это странно) Либо назови по названию приложения, либо просто App (обычно используют второе)

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/main/NewsAdapter.kt
> +        holder.binding.itemNews.setOnClickListener {
Так как байнд холдера вызывается часто, то ты часто переприсваеваешь листенер у новости + каждый раз создаешь новую лямбду

Кликлистенеры холдера нужно создавать внутри init блока в самом холдере. В качестве аргумента холдер передает свою позицию (параметр bindingAdapterPosition)

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/main/NewsAdapter.kt
> +fun interface OnItemClickListener {
Вместо функционального интерфейса, можно просто указать тип лямбды `(idItem: Int) -> Unit`

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/utils/DateUtils.kt
> +fun correctDateTime(startDateTime: Long, endDateTime: Long): String {
Оставляй комментарии в виде JavaDoc к утилитарным методам

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/di/AppModule.kt
Круто, что сразу начал разбивать на модули! Выноси в собственные модули вьюмодели и репозитории (ViewModelModule и тд)

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/data/db/HelpCategoryRepository.kt
> +    fun getHelpCategory(): List<HelpCategory>
во множественном числе

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/data/HelpCategoryRepositoryImpl.kt
> +    override fun changeEnabledItemById(idItem: Int) {
Убери фильтрацию на уровень вьюмодели. Репозиторий должен хранить только логику для получения данных, не обработку.

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/data/HelpCategoryRepositoryImpl.kt
> +    private val _listHelpCategory = mutableListOf<HelpCategory>()
Мутабельность списка тоже убери, обычно данные получаемые репозиторием (из бд и сети) не мутабельны

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/data/entity/HelpCategory.kt
> +    @SerializedName("icon_url") val iconUrl: Int,
Везде где используешь SerializedName:
1) Ставь аннотацию на все поля, даже на те, название которых совпадает с json (так как обфускаторы уничтожают названия, gson потом не сможет распарсить)
2) Пиши аннотацию не слева от переменной, а НАД ней

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/data/NewsRepositoryImpl.kt
> +    override fun getNewsByFilter(filter: List<Int>): List<News> {
Убираем логику из репозитория

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/data/NewsRepositoryImpl.kt
> +    private val _listNews = mutableListOf<News>()
Мутабельность тоже убираем. Этот список вообще не нужен тут, у тебя же данные берутся из ассетов, с ними и работай

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/data/NewsRepositoryImpl.kt
> +    override fun addNews(news: News) {
Добавление новостей? В тз такого нет

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/data/NewsRepositoryImpl.kt
> +    override fun getNewsById(newsId: Int): News? {
логику убираем

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/filter/FilterAdapter.kt
> +class FilterAdapter : RecyclerView.Adapter<FilterViewHolder>() {
Замечания аналогичные адаптеру новостей

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/main/NewsFragment.kt
> +        mainViewModel.setHideBottomNavigation(false)
Да, отлично сделано) Однако, согласись, не особо удобно?) 
Есть способ как сделать удобнее. Можешь подумать самостоятельно, а можешь спросить как сделать)

(если не видишь тут никаких проблем, то оставляй так)

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/res/layout/fragment_filter.xml
> +    <RelativeLayout
Relative? Да еще и внутри линеара? Мне кажется производительность просидает. Лучше уж через констрейнт сделать

2023-07-02 17:25 UTC, RebootSTR commented on app/src/main/res/values/style.xml
> +        <item name="android:fontFamily">@font/roboto_regular</item>
![image](https://github.com/ArkHak/SimbirSoftRepo/assets/46527979/db51ca10-15a2-4736-88c6-292942cb2f5d)

2023-07-04 17:29 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/SimbirSoftApplication.kt
> +class SimbirSoftApplication : Application() {
ну приложении и называлось))

2023-07-04 18:39 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/main/NewsAdapter.kt
> +        holder.binding.itemNews.setOnClickListener {
+++

2023-07-04 18:39 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/main/NewsAdapter.kt
> +fun interface OnItemClickListener {
++

2023-07-04 19:04 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/utils/DateUtils.kt
> +fun correctDateTime(startDateTime: Long, endDateTime: Long): String {
+++

2023-07-04 19:07 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/di/AppModule.kt
+++

2023-07-04 19:10 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/data/db/HelpCategoryRepository.kt
> +    fun getHelpCategory(): List<HelpCategory>
++

2023-07-04 19:16 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/data/HelpCategoryRepositoryImpl.kt
> +    override fun changeEnabledItemById(idItem: Int) {
если я правильно понял - то убрал

2023-07-04 20:20 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/data/HelpCategoryRepositoryImpl.kt
> +    private val _listHelpCategory = mutableListOf<HelpCategory>()
++

2023-07-04 20:22 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/data/entity/HelpCategory.kt
> +    @SerializedName("icon_url") val iconUrl: Int,
++

2023-07-04 20:47 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/data/NewsRepositoryImpl.kt
> +    override fun getNewsByFilter(filter: List<Int>): List<News> {
++

2023-07-04 21:03 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/data/NewsRepositoryImpl.kt
> +    private val _listNews = mutableListOf<News>()
private val _listNews = getNewsFromAssets() оставил так

2023-07-04 21:04 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/data/NewsRepositoryImpl.kt
> +    override fun addNews(news: News) {
думал наперед)
CRUD))))

2023-07-04 21:12 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/data/NewsRepositoryImpl.kt
> +    override fun getNewsById(newsId: Int): News? {
+++

2023-07-04 21:28 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/filter/FilterAdapter.kt
> +class FilterAdapter : RecyclerView.Adapter<FilterViewHolder>() {
+++

2023-07-04 21:37 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/main/NewsFragment.kt
> +        mainViewModel.setHideBottomNavigation(false)
+-

2023-07-04 21:40 UTC, ArkHak commented on app/src/main/res/layout/fragment_filter.xml
> +    <RelativeLayout
+++ убрал Relative

2023-07-04 21:47 UTC, ArkHak commented on app/src/main/res/values/style.xml
> +        <item name="android:fontFamily">@font/roboto_regular</item>
++

2023-07-09 14:36 UTC, RebootSTR commented
Исправь картинки в детальной новости и можешь вливать (подробности в тг)

2023-07-09 16:15 UTC, merged