Concurrency
ArkHak/SimbirSoftRepo pull request #9
Opened 2023-07-10 20:05 UTC by ArkHak

- added data loading via Executors in HelpFragment;
- added data loading via Service in NewsFragment;

2023-07-17 07:19 UTC, RebootSTR requested changes
Категории грузятся нормально, а вот новости проверить не могу, получаю краш на своем тестовом устройстве. Подробнее смотри в комментариях

2023-07-17 07:19 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/main/NewsViewModel.kt
> +    private val context: Context,
пробрасывать контекст в вьюмодель не очень хорошая идея. Лучше работать со стартом сервисов и бродкастами на уровне фрагмента

2023-07-17 07:19 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/main/NewsViewModel.kt
> +        @RequiresApi(Build.VERSION_CODES.TIRAMISU)
Эта ошибка означает, что метод будет работать только на API 33 и выше. Для остальных версий андроида тебя ждет краш. Аннотация не спасает

![image](https://github.com/ArkHak/SimbirSoftRepo/assets/46527979/94896f4a-4aa1-44c2-9bda-0e0480298a6d)

2023-07-17 07:19 UTC, RebootSTR commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/main/NewsFragment.kt
> +        private var serviceInit = false
Почему эта переменная в статической области?

2023-07-17 21:08 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/main/NewsViewModel.kt
> +    private val context: Context,
подправил

2023-07-17 21:08 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/main/NewsViewModel.kt
> +        @RequiresApi(Build.VERSION_CODES.TIRAMISU)
+++

2023-07-17 21:08 UTC, ArkHak commented on app/src/main/java/o/mysin/simbirsoftappjava/ui/news/main/NewsFragment.kt
> +        private var serviceInit = false
+++

2023-07-24 06:43 UTC, RebootSTR commented
Прокидывание новостей из ui в data слой, для того чтобы отправить их обратно на ui выглядит очень странно, но понимаю что ты просто не хотел удалять то что уже было написано, поэтому все хорошо. Закрыл задание

2023-07-24 06:44 UTC, RebootSTR approved these changes

2023-07-24 17:30 UTC, merged